security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                target: app_login


    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/services, roles: PUBLIC_ACCESS }
        - { path: ^/service/, roles: PUBLIC_ACCESS }
        - { path: ^/goudurix-dashboard, roles: PUBLIC_ACCESS }
        - { path: ^/risque/, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_AGENT }

    role_hierarchy:
        ROLE_ADMIN: ROLE_AGENT
