[phases.setup]
nixPkgs = ["php82", "composer", "nodejs-18_x"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.build]
cmds = [
  "php bin/console cache:clear --env=prod --no-debug"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
